apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-config
  namespace: security
data:
  acquis.yaml: |
    filenames:
    - /var/log/traefik/*.log
    labels:
      type: traefik
  config.yaml: |
    api:
      server:
        listen_uri: "0.0.0.0:8080"
        listen_port: 8080
        console: false
      profiles:
        - name: default
          filters: ""
    db:
      type: sqlite
      db_path: /var/lib/crowdsec/data/crowdsec.db
    log:
      level: info
    prometheus:
      enabled: false