apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-notifications
  namespace: security
data:
  http.yaml: |
    type: http
    name: http_default
    log_level: info
    format: |
      {{.|toJson}}
    url: http://n8n.n8n.svc.cluster.local:5678/webhook/crowdsec-alert
    method: POST
    skip_tls_verification: false
    headers:
      Content-Type: application/json
  profiles.yaml: |
    name: default_ip_remediation
    filters:
    - Alert.Remediation == true && Alert.GetScope() == "Ip"
    decisions:
    - type: ban
      duration: 4h
    notifications:
    - http_default
    on_success: break
    ---
    name: default_range_remediation
    filters:
    - Alert.Remediation == true && Alert.GetScope() == "Range"
    decisions:
    - type: ban
      duration: 4h
    notifications:
    - http_default
    on_success: break